--------------------------------------------------------
--  Arquivo criado - sábado-março-12-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SQ_BAIRRO_CODIGO
--------------------------------------------------------

   CREATE SEQUENCE  "GUSTAVO"."SQ_BAIRRO_CODIGO"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 11 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_CARGO_CODIGO
--------------------------------------------------------

   CREATE SEQUENCE  "GUSTAVO"."SQ_CARGO_CODIGO"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 8 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_CIDADE_CODIGO
--------------------------------------------------------

   CREATE SEQUENCE  "GUSTAVO"."SQ_CIDADE_CODIGO"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 7 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_DOCUMENTOTIPO_CODIGO
--------------------------------------------------------

   CREATE SEQUENCE  "GUSTAVO"."SQ_DOCUMENTOTIPO_CODIGO"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 5 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_ENDERECO_CODIGO
--------------------------------------------------------

   CREATE SEQUENCE  "GUSTAVO"."SQ_ENDERECO_CODIGO"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 15 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_ESTADO_CODIGO
--------------------------------------------------------

   CREATE SEQUENCE  "GUSTAVO"."SQ_ESTADO_CODIGO"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 6 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_PROFESSIONAL_CODIGO
--------------------------------------------------------

   CREATE SEQUENCE  "GUSTAVO"."SQ_PROFESSIONAL_CODIGO"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 94 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_PROFISSAO_CODIGO
--------------------------------------------------------

   CREATE SEQUENCE  "GUSTAVO"."SQ_PROFISSAO_CODIGO"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQ_VINCULOTIPO_CODIGO
--------------------------------------------------------

   CREATE SEQUENCE  "GUSTAVO"."SQ_VINCULOTIPO_CODIGO"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 6 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CARGO
--------------------------------------------------------

  CREATE TABLE "GUSTAVO"."CARGO" 
   (	"CODIGO" NUMBER(4,0), 
	"NOME" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DOCUMENTOTIPO
--------------------------------------------------------

  CREATE TABLE "GUSTAVO"."DOCUMENTOTIPO" 
   (	"CODIGO" NUMBER(4,0), 
	"NOME" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ENDERECO
--------------------------------------------------------

  CREATE TABLE "GUSTAVO"."ENDERECO" 
   (	"CODIGO" NUMBER(4,0), 
	"ID_PROFISSIONAL" NUMBER(*,0), 
	"BAIRRO" VARCHAR2(100 BYTE), 
	"CIDADE" VARCHAR2(100 BYTE), 
	"LOGRADOURO" VARCHAR2(100 BYTE), 
	"CEP" VARCHAR2(15 BYTE), 
	"ESTADO" VARCHAR2(4 BYTE), 
	"NUMERO" VARCHAR2(5 BYTE), 
	"COMPLEMENTO" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROFISSAO
--------------------------------------------------------

  CREATE TABLE "GUSTAVO"."PROFISSAO" 
   (	"CODIGO" NUMBER(4,0), 
	"NOME" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROFISSIONAL
--------------------------------------------------------

  CREATE TABLE "GUSTAVO"."PROFISSIONAL" 
   (	"CODIGO" NUMBER(4,0), 
	"DATACAD" DATE, 
	"NOME" VARCHAR2(40 BYTE), 
	"SEXO" CHAR(1 BYTE), 
	"DATANASC" DATE, 
	"TELFIXO" VARCHAR2(12 BYTE), 
	"TELCEL" VARCHAR2(13 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"RG" VARCHAR2(14 BYTE), 
	"CPF" VARCHAR2(14 BYTE), 
	"CTPS" VARCHAR2(8 BYTE), 
	"PROFISSAO" NUMBER(4,0), 
	"DOCUMENTOTIPO" NUMBER(4,0), 
	"DOCUMENTONR" VARCHAR2(18 BYTE), 
	"DOCUMENTOVAL" DATE, 
	"CARGO" NUMBER(4,0), 
	"SALARIO" NUMBER(6,2), 
	"VINCULOTIPO" NUMBER(4,0), 
	"STATUS" CHAR(1 BYTE), 
	"OBS" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VINCULOTIPO
--------------------------------------------------------

  CREATE TABLE "GUSTAVO"."VINCULOTIPO" 
   (	"CODIGO" NUMBER(4,0), 
	"NOME" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into GUSTAVO.CARGO
SET DEFINE OFF;
Insert into GUSTAVO.CARGO (CODIGO,NOME) values ('1','Não Informado');
Insert into GUSTAVO.CARGO (CODIGO,NOME) values ('2','Análista de Sistemas Junior');
Insert into GUSTAVO.CARGO (CODIGO,NOME) values ('3','Análista de Sistemas Master');
Insert into GUSTAVO.CARGO (CODIGO,NOME) values ('4','Engenheiro (a) Elétrico');
Insert into GUSTAVO.CARGO (CODIGO,NOME) values ('5','Médico Residente');
Insert into GUSTAVO.CARGO (CODIGO,NOME) values ('6','Análista Jurídico');
Insert into GUSTAVO.CARGO (CODIGO,NOME) values ('7','Estágiario Jurídico');
REM INSERTING into GUSTAVO.DOCUMENTOTIPO
SET DEFINE OFF;
Insert into GUSTAVO.DOCUMENTOTIPO (CODIGO,NOME) values ('1','Não Informado');
Insert into GUSTAVO.DOCUMENTOTIPO (CODIGO,NOME) values ('2','CRM');
Insert into GUSTAVO.DOCUMENTOTIPO (CODIGO,NOME) values ('3','OAB');
Insert into GUSTAVO.DOCUMENTOTIPO (CODIGO,NOME) values ('4','CREA');
REM INSERTING into GUSTAVO.ENDERECO
SET DEFINE OFF;
Insert into GUSTAVO.ENDERECO (CODIGO,ID_PROFISSIONAL,BAIRRO,CIDADE,LOGRADOURO,CEP,ESTADO,NUMERO,COMPLEMENTO) values ('13','92','Bairro teste','SÃÂ£o Paulo','Casa Teste','45645-454','SP','66','test');
Insert into GUSTAVO.ENDERECO (CODIGO,ID_PROFISSIONAL,BAIRRO,CIDADE,LOGRADOURO,CEP,ESTADO,NUMERO,COMPLEMENTO) values ('10','25','Cidade ipava','São Paulo','Rua catanguá','04951-020','SP','77','casa');
Insert into GUSTAVO.ENDERECO (CODIGO,ID_PROFISSIONAL,BAIRRO,CIDADE,LOGRADOURO,CEP,ESTADO,NUMERO,COMPLEMENTO) values ('14','93','Bairro Teste','Cidade Teste','casa TESte','32586-121','SP','365','teste');
REM INSERTING into GUSTAVO.PROFISSAO
SET DEFINE OFF;
Insert into GUSTAVO.PROFISSAO (CODIGO,NOME) values ('1','Não Informado');
Insert into GUSTAVO.PROFISSAO (CODIGO,NOME) values ('2','Analista de Sistemas');
Insert into GUSTAVO.PROFISSAO (CODIGO,NOME) values ('3','Médico (a)');
Insert into GUSTAVO.PROFISSAO (CODIGO,NOME) values ('4','Dentista');
Insert into GUSTAVO.PROFISSAO (CODIGO,NOME) values ('5','Advogado (a)');
Insert into GUSTAVO.PROFISSAO (CODIGO,NOME) values ('6','Engenheiro (a) Cívil');
Insert into GUSTAVO.PROFISSAO (CODIGO,NOME) values ('7','Engenheiro (a) Elétrico');
Insert into GUSTAVO.PROFISSAO (CODIGO,NOME) values ('8','Agronomia');
Insert into GUSTAVO.PROFISSAO (CODIGO,NOME) values ('9','Biotecnologia');
Insert into GUSTAVO.PROFISSAO (CODIGO,NOME) values ('10','Ecologia');
Insert into GUSTAVO.PROFISSAO (CODIGO,NOME) values ('11','Engenharia Ambiental');
Insert into GUSTAVO.PROFISSAO (CODIGO,NOME) values ('12','Engenharia de Pesca');
Insert into GUSTAVO.PROFISSAO (CODIGO,NOME) values ('13','Engenharia Hídrica');
Insert into GUSTAVO.PROFISSAO (CODIGO,NOME) values ('14','Gestão Ambiental');
Insert into GUSTAVO.PROFISSAO (CODIGO,NOME) values ('15','Geologia');
Insert into GUSTAVO.PROFISSAO (CODIGO,NOME) values ('16','Oceanografia');
Insert into GUSTAVO.PROFISSAO (CODIGO,NOME) values ('17','Engenharia Agrícola');
Insert into GUSTAVO.PROFISSAO (CODIGO,NOME) values ('18','Engenharia de Energia');
Insert into GUSTAVO.PROFISSAO (CODIGO,NOME) values ('19','Engenharia Florestal');
Insert into GUSTAVO.PROFISSAO (CODIGO,NOME) values ('20','Medicina Veterinária');
Insert into GUSTAVO.PROFISSAO (CODIGO,NOME) values ('21','Meteorologia');
Insert into GUSTAVO.PROFISSAO (CODIGO,NOME) values ('22','Zootecnia');
Insert into GUSTAVO.PROFISSAO (CODIGO,NOME) values ('23','Bioquímica');
Insert into GUSTAVO.PROFISSAO (CODIGO,NOME) values ('24','Biomedicina');
Insert into GUSTAVO.PROFISSAO (CODIGO,NOME) values ('25','Ciências Biológicas');
Insert into GUSTAVO.PROFISSAO (CODIGO,NOME) values ('26','Educação Física');
Insert into GUSTAVO.PROFISSAO (CODIGO,NOME) values ('27','Enfermagem');
Insert into GUSTAVO.PROFISSAO (CODIGO,NOME) values ('28','Estética');
Insert into GUSTAVO.PROFISSAO (CODIGO,NOME) values ('29','Farmácia');
Insert into GUSTAVO.PROFISSAO (CODIGO,NOME) values ('30','Fisioterapia');
Insert into GUSTAVO.PROFISSAO (CODIGO,NOME) values ('31','Fonoaudiologia');
Insert into GUSTAVO.PROFISSAO (CODIGO,NOME) values ('32','Gerontologia');
Insert into GUSTAVO.PROFISSAO (CODIGO,NOME) values ('33','Musicoterapia');
Insert into GUSTAVO.PROFISSAO (CODIGO,NOME) values ('34','Nutrição');
Insert into GUSTAVO.PROFISSAO (CODIGO,NOME) values ('35','Obstetrícial');
Insert into GUSTAVO.PROFISSAO (CODIGO,NOME) values ('36','Odontologia');
Insert into GUSTAVO.PROFISSAO (CODIGO,NOME) values ('37','Quiropraxia');
Insert into GUSTAVO.PROFISSAO (CODIGO,NOME) values ('38','Radiologia');
Insert into GUSTAVO.PROFISSAO (CODIGO,NOME) values ('39','Saúde Coletiva');
Insert into GUSTAVO.PROFISSAO (CODIGO,NOME) values ('40','Terapia Ocupacional');
REM INSERTING into GUSTAVO.PROFISSIONAL
SET DEFINE OFF;
Insert into GUSTAVO.PROFISSIONAL (CODIGO,DATACAD,NOME,SEXO,DATANASC,TELFIXO,TELCEL,EMAIL,RG,CPF,CTPS,PROFISSAO,DOCUMENTOTIPO,DOCUMENTONR,DOCUMENTOVAL,CARGO,SALARIO,VINCULOTIPO,STATUS,OBS) values ('25',to_date('06/03/22','DD/MM/RR'),'GUSTAVO MACEDO','M',to_date('10/06/01','DD/MM/RR'),'15-6548-4848','11-93463-4668','gustavo@gmail.com','987654321-5','123.456.789-66','56.465-4','5','4','36595',to_date('25/09/30','DD/MM/RR'),'2','6500','4','A',' ');
Insert into GUSTAVO.PROFISSIONAL (CODIGO,DATACAD,NOME,SEXO,DATANASC,TELFIXO,TELCEL,EMAIL,RG,CPF,CTPS,PROFISSAO,DOCUMENTOTIPO,DOCUMENTONR,DOCUMENTOVAL,CARGO,SALARIO,VINCULOTIPO,STATUS,OBS) values ('93',to_date('11/03/22','DD/MM/RR'),'TESTE EDITAR 93','M',to_date('20/08/98','DD/MM/RR'),'12-3456-7983','98-79877-8888','teste93@gmail','369852147','789.321.456-02','36.522-2','2','1','36524',to_date('10/06/23','DD/MM/RR'),'2','8000','2','A',' ');
Insert into GUSTAVO.PROFISSIONAL (CODIGO,DATACAD,NOME,SEXO,DATANASC,TELFIXO,TELCEL,EMAIL,RG,CPF,CTPS,PROFISSAO,DOCUMENTOTIPO,DOCUMENTONR,DOCUMENTOVAL,CARGO,SALARIO,VINCULOTIPO,STATUS,OBS) values ('92',to_date('10/03/22','DD/MM/RR'),'TESTE 40','M',to_date('10/09/01','DD/MM/RR'),'11-1111-1111','23-33333-3333','teste@gmail','6988778','321.654.987-77','36.952-1','2','1','365205',to_date('20/09/30','DD/MM/RR'),'2','7000','2','A',' ');
REM INSERTING into GUSTAVO.VINCULOTIPO
SET DEFINE OFF;
Insert into GUSTAVO.VINCULOTIPO (CODIGO,NOME) values ('1','Não Informado');
Insert into GUSTAVO.VINCULOTIPO (CODIGO,NOME) values ('2','CLT');
Insert into GUSTAVO.VINCULOTIPO (CODIGO,NOME) values ('3','Contrato temporário');
Insert into GUSTAVO.VINCULOTIPO (CODIGO,NOME) values ('4','Contrato de trabalho');
Insert into GUSTAVO.VINCULOTIPO (CODIGO,NOME) values ('5','Estágio');
--------------------------------------------------------
--  DDL for Index PK_CARGO
--------------------------------------------------------

  CREATE UNIQUE INDEX "GUSTAVO"."PK_CARGO" ON "GUSTAVO"."CARGO" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_PROFISSAO
--------------------------------------------------------

  CREATE UNIQUE INDEX "GUSTAVO"."PK_PROFISSAO" ON "GUSTAVO"."PROFISSAO" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_ENDERECO
--------------------------------------------------------

  CREATE UNIQUE INDEX "GUSTAVO"."PK_ENDERECO" ON "GUSTAVO"."ENDERECO" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CPF_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "GUSTAVO"."CPF_UNIQUE" ON "GUSTAVO"."PROFISSIONAL" ("CPF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RG_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "GUSTAVO"."RG_UNIQUE" ON "GUSTAVO"."PROFISSIONAL" ("RG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_DOCUMENTOTIPO
--------------------------------------------------------

  CREATE UNIQUE INDEX "GUSTAVO"."PK_DOCUMENTOTIPO" ON "GUSTAVO"."DOCUMENTOTIPO" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_PROFISSIONAL
--------------------------------------------------------

  CREATE UNIQUE INDEX "GUSTAVO"."PK_PROFISSIONAL" ON "GUSTAVO"."PROFISSIONAL" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_VINCULOTIPO
--------------------------------------------------------

  CREATE UNIQUE INDEX "GUSTAVO"."PK_VINCULOTIPO" ON "GUSTAVO"."VINCULOTIPO" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger TR_CARGO_CODIGO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "GUSTAVO"."TR_CARGO_CODIGO" 
BEFORE INSERT ON cargo
FOR EACH ROW
BEGIN
    SELECT sq_cargo_codigo.nextval INTO :NEW.codigo from dual;
END;
/
ALTER TRIGGER "GUSTAVO"."TR_CARGO_CODIGO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TR_DOCUMENTOTIPO_CODIGO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "GUSTAVO"."TR_DOCUMENTOTIPO_CODIGO" 
BEFORE INSERT ON documentotipo
FOR EACH ROW
BEGIN
    SELECT sq_documentotipo_codigo.nextval INTO :NEW.codigo from dual;
END;
/
ALTER TRIGGER "GUSTAVO"."TR_DOCUMENTOTIPO_CODIGO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TR_ENDERECO_CODIGO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "GUSTAVO"."TR_ENDERECO_CODIGO" 
BEFORE INSERT ON endereco
FOR EACH ROW
BEGIN
SELECT sq_endereco_codigo.nextval into :NEW.codigo from dual;
END;
/
ALTER TRIGGER "GUSTAVO"."TR_ENDERECO_CODIGO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TR_PROFISSAO_CODIGO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "GUSTAVO"."TR_PROFISSAO_CODIGO" 
BEFORE INSERT ON profissao
FOR EACH ROW
BEGIN
    SELECT sq_profissao_codigo.nextval INTO :NEW.codigo from dual;
END;
/
ALTER TRIGGER "GUSTAVO"."TR_PROFISSAO_CODIGO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TR_PROFISSIONAL_CODIGO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "GUSTAVO"."TR_PROFISSIONAL_CODIGO" 
BEFORE INSERT ON profissional
FOR EACH ROW
BEGIN
SELECT sq_professional_codigo.nextval INTO :NEW.codigo from dual;
END;
/
ALTER TRIGGER "GUSTAVO"."TR_PROFISSIONAL_CODIGO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TR_VINCULOTIPO_CODIGO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "GUSTAVO"."TR_VINCULOTIPO_CODIGO" 
BEFORE INSERT ON vinculotipo
FOR EACH ROW
BEGIN
    SELECT sq_vinculotipo_codigo.nextval INTO :NEW.codigo from dual;
END;
/
ALTER TRIGGER "GUSTAVO"."TR_VINCULOTIPO_CODIGO" ENABLE;
--------------------------------------------------------
--  Constraints for Table PROFISSIONAL
--------------------------------------------------------

  ALTER TABLE "GUSTAVO"."PROFISSIONAL" ADD CONSTRAINT "CPF_UNIQUE" UNIQUE ("CPF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GUSTAVO"."PROFISSIONAL" ADD CONSTRAINT "RG_UNIQUE" UNIQUE ("RG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GUSTAVO"."PROFISSIONAL" ADD CONSTRAINT "PK_PROFISSIONAL" PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GUSTAVO"."PROFISSIONAL" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "GUSTAVO"."PROFISSIONAL" MODIFY ("CODIGO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VINCULOTIPO
--------------------------------------------------------

  ALTER TABLE "GUSTAVO"."VINCULOTIPO" ADD CONSTRAINT "PK_VINCULOTIPO" PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GUSTAVO"."VINCULOTIPO" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "GUSTAVO"."VINCULOTIPO" MODIFY ("CODIGO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CARGO
--------------------------------------------------------

  ALTER TABLE "GUSTAVO"."CARGO" ADD CONSTRAINT "PK_CARGO" PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GUSTAVO"."CARGO" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "GUSTAVO"."CARGO" MODIFY ("CODIGO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ENDERECO
--------------------------------------------------------

  ALTER TABLE "GUSTAVO"."ENDERECO" ADD CONSTRAINT "PK_ENDERECO" PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GUSTAVO"."ENDERECO" MODIFY ("ID_PROFISSIONAL" NOT NULL ENABLE);
  ALTER TABLE "GUSTAVO"."ENDERECO" MODIFY ("CODIGO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROFISSAO
--------------------------------------------------------

  ALTER TABLE "GUSTAVO"."PROFISSAO" ADD CONSTRAINT "PK_PROFISSAO" PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GUSTAVO"."PROFISSAO" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "GUSTAVO"."PROFISSAO" MODIFY ("CODIGO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DOCUMENTOTIPO
--------------------------------------------------------

  ALTER TABLE "GUSTAVO"."DOCUMENTOTIPO" ADD CONSTRAINT "PK_DOCUMENTOTIPO" PRIMARY KEY ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GUSTAVO"."DOCUMENTOTIPO" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "GUSTAVO"."DOCUMENTOTIPO" MODIFY ("CODIGO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ENDERECO
--------------------------------------------------------

  ALTER TABLE "GUSTAVO"."ENDERECO" ADD CONSTRAINT "ENDERECO_PROFISSIONAL_ID_FK" FOREIGN KEY ("ID_PROFISSIONAL")
	  REFERENCES "GUSTAVO"."PROFISSIONAL" ("CODIGO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROFISSIONAL
--------------------------------------------------------

  ALTER TABLE "GUSTAVO"."PROFISSIONAL" ADD CONSTRAINT "CARGO_COD_FK" FOREIGN KEY ("CARGO")
	  REFERENCES "GUSTAVO"."CARGO" ("CODIGO") ENABLE;
  ALTER TABLE "GUSTAVO"."PROFISSIONAL" ADD CONSTRAINT "DOCUMENTOTIPO_COD_FK" FOREIGN KEY ("DOCUMENTOTIPO")
	  REFERENCES "GUSTAVO"."DOCUMENTOTIPO" ("CODIGO") ENABLE;
  ALTER TABLE "GUSTAVO"."PROFISSIONAL" ADD CONSTRAINT "PROFISSAO_COD_FK" FOREIGN KEY ("PROFISSAO")
	  REFERENCES "GUSTAVO"."PROFISSAO" ("CODIGO") ENABLE;
  ALTER TABLE "GUSTAVO"."PROFISSIONAL" ADD CONSTRAINT "VINCULOTIPO_COD_FK" FOREIGN KEY ("VINCULOTIPO")
	  REFERENCES "GUSTAVO"."VINCULOTIPO" ("CODIGO") ENABLE;
